import pygame
pygame.init()
pygame.font.init()
spriteparado1 = pygame.image.load('sprites/personagem frame 1.png')
spriteparado2 = pygame.image.load('sprites/personagem frame 2.png')
spriteparado3 = pygame.image.load('sprites/personagem frame 3.png')
spriteparado1esquerda = pygame.image.load('sprites/personagem parado1 esquerda.png')
spriteparado2esquerda = pygame.image.load('sprites/personagem parado2 esquerda.png')
spriteparado3esquerda = pygame.image.load('sprites/personagem parado3 esquerda.png')
spriterun1 = pygame.image.load('sprites/personagem correndo frame 1.png')
spriterun2 = pygame.image.load('sprites/personagem correndo frame 2.png')
spriterun3 = pygame.image.load('sprites/personagem correndo frame 3.png')
spriterun4 = pygame.image.load('sprites/personagem correndo frame 4.png')
spriterun1esquerda = pygame.image.load('sprites/personagem correndo frame 1 esquerda.png')
spriterun2esquerda = pygame.image.load('sprites/personagem correndo frame 2 esquerda.png')
spriterun3esquerda = pygame.image.load('sprites/personagem correndo frame 3 esquerda.png')
spriterun4esquerda = pygame.image.load('sprites/personagem correndo frame 4 esquerda.png')
grasstile = pygame.image.load('sprites/grass tile.png')
soiltile = pygame.image.load('sprites/soil tile.png')
dayskytile = pygame.image.load('sprites/dayskytile.png')
pulofrente1= pygame.image.load('sprites/personagem pulando frente 1.png')
pulofrente2= pygame.image.load('sprites/personagem pulando frente 2.png')
pulofrente3= pygame.image.load('sprites/personagem pulando frente 3.png')
pulotras1= pygame.image.load('sprites/personagem pulando tras 1.png')
pulotras2= pygame.image.load('sprites/personagem pulando tras 2.png')
pulotras3= pygame.image.load('sprites/personagem pulando tras 3.png')
nuvem1=pygame.image.load('sprites/nuvem1.png')
nuvem2=pygame.image.load('sprites/nuvem2.png')
nuvem3=pygame.image.load('sprites/nuvem3.png')
nuvem4=pygame.image.load('sprites/nuvem4.png')
nuvem5=pygame.image.load('sprites/nuvem5.png')
sol=pygame.image.load('sprites/sol.png')
cenário1=pygame.image.load('sprites/cenário1.png')